### ISSUE TITLE
Link to archive.org for tor_v10.5.10_en

### ISSUE THREAD

**Issue by n0tduck1e** [machevalia/pwndb.sh#1]
Hey,

i had to access a v2 onion link and was in search  for older version of tor and found your google drive link , i was scared af to use your google drive so further search and found perfectly good url on archive.org (mentioned below.).

am creating this post for two reasons
1. The google drive tor client is fine. md5 sum matches with archive.org so for people like me: you can trust it.
2. Please add this archive.org link also in readme so people can have another backup in case google drive link doesnt work.

Thank you for this repo and your google drive backup :)

https://web.archive.org/web/20211104213819if_/https://dist.torproject.org/torbrowser/10.5.10/tor-browser-linux64-10.5.10_en-US.tar.xz

4f61ebcd1e73150dc244f73d3c4ce6d8  tor-browser-linux64-10.5.10_en-US.tar.xz (from archive.org)
4f61ebcd1e73150dc244f73d3c4ce6d8  tor-browser-linux64-10.5.10_en-US.tar.xz (from google drive)

**Comment by machevalia** [comment]
Thanks for the heads up. In the rush to make this I hadn't even thought to check archive.org. Much appreciated and thanks for validating the hash of my drive file!

**Comment by machevalia** [comment]
Added link to readme and re-ordered the downloads to make the Drive link last. Pinning for others to see hash comparison by 3rd party. 

Thanks @not-duckie
