### ISSUE TITLE
The onion link is down :/

### ISSUE THREAD

**Issue by 5l1v3r1** [machevalia/pwndb.sh#2]
I tried with 10.5 version of tor and the link http://pwndb2am4tzkvold.onion is down again :/

**Comment by machevalia** [comment]
Yeah, it looks like it went down a few days ago. You can monitor status here from the public network - https://onion.live/site/pwndb

Additionally, if you register for an account you can use DeepSearch which I don't find as reliable in terms of results but you might get something worthwhile http://xjypo5vzgmo7jca6b322dnqbsdnp3amd24ybx26x5nxbusccjkm4pwid.onion/
